name: Update Countdown SVG

on:
  schedule:
    - cron: "0 * * * *"  # 每小时更新一次
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run countdown script
        run: |
          python countdown.py

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add assets/countdown.svg
          git diff --quiet || (git commit -m "Update countdown" && git push)
